create database BDRUC;
use BDRUC;
use APIDATAOFICIAL;
CREATE TABLE contribuyentesRUC (
    ruc VARCHAR(11) PRIMARY KEY,
    nombre_razon_social VARCHAR(100),
    estado_contribuyente VARCHAR(20),
    condicion_domicilio VARCHAR(20),
    ubigeo VARCHAR(6),
    tipo_via VARCHAR(50),
    nombre_via VARCHAR(100),
    codigo_zona VARCHAR(10),
    tipo_zona VARCHAR(50),
    numero VARCHAR(10),
    interior VARCHAR(10),
    lote VARCHAR(10),
    departamento VARCHAR(10),
    manzana VARCHAR(10),
    kilometro VARCHAR(10)
);


INSERT INTO contribuyentesRUC (ruc, nombre_razon_social, estado_contribuyente, condicion_domicilio, ubigeo, tipo_via, nombre_via, codigo_zona, tipo_zona, numero, interior, lote, departamento, manzana, kilometro) VALUES
('10452159428', 'GARCIA CHANCO CARLOS AUGUSTO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10806173695', 'TOQUE GOMEZ ALEJANDRO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),	
('10758072075', 'RAMIREZ VALVERDE DAVID ELIAS', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10100214283', 'FERNANDEZ OSORIO CARLA GUADALUPE', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10463572734', 'DAZA ROSALES GILDER', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10467658099', 'FIESTAS CHERRE JAVIER SEBASTIAN', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10198672004', 'QUISPE CAMAYO BERNARDINA', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10463982711', 'SONCCO MAMANI IRMA', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10293373685', 'CASANI BARBACHAN LUIS ANTONIO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10462067912', 'CRUZ BALLON JEAN GABRIEL', 'ACTIVO', 'PENDIENTE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10446716005', 'VILCA ARIAS RENZO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10097476646', 'GUZMAN ROLDAN GLORIA ROCIO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10423882471', 'CALDERON BERROSPI MICHAEL JONATAN', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10483511171', 'DIAZ LIZA LIZBETH', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10427040319', 'GUERRERO ROSALES JUSTINO PEDRO', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10753654165', 'CABANA TITO KARIN TATIANA', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('10458044924', 'HUAYMACARI VARGAS ROBERT', 'ACTIVO', 'HABIDO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

select * from contribuyentesRUC;


select * from  user;
create table user(
id int primary key,
name varchar(50),
email varchar(100),
password varchar(100)
)
